
// This file is automatically generated by the deployment script
// However, since we are patching the system live, we define the structure here.
// The real values will be populated by the updated deploy script.

export interface ContractsConfig {
    complianceAddress: string;
    tokenAddress: string;
    oracleAddress: string;
    dexAddress: string;
    networkId: string;
}

export const ContractABIs = {
    // We will load these from the JSON files or hardcode minimal interfaces
    // For simplicity in this hotfix, we can use minimal human-readable ABIs
    ComplianceRegistry: [
        "function addToWhitelist(address _account) external",
        "function removeFromWhitelist(address _account) external",
        "function isVerified(address _account) external view returns (bool)",
        "function addToBlacklist(address _account) external"
    ],
    AssetToken: [
        "function balanceOf(address account) external view returns (uint256)",
        "function approve(address spender, uint256 amount) external returns (bool)",
        "function transfer(address to, uint256 amount) external returns (bool)",
        "function allowance(address owner, address spender) external view returns (uint256)",
        "function symbol() external view returns (string)",
        "function decimals() external view returns (uint8)"
    ],
    AssetNFT: [
        "function balanceOf(address account) external view returns (uint256)",
        "function ownerOf(uint256 tokenId) external view returns (address)",
        "function tokenURI(uint256 tokenId) external view returns (string)",
        "function transferFrom(address from, address to, uint256 tokenId) external",
        "function buyNFT(string memory _uri) external payable",
        "function mintedURIs(string memory _uri) external view returns (bool)"
    ],
    SimpleDEX: [
        "function buyTokens() external payable",
        "function sellTokens(uint256 amount) external",
        "function price() external view returns (uint256)"
    ],
    AssetOracle: [
        "function getPrice(string memory symbol) external view returns (uint256)"
    ]
};
